package com.rest.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Pessoa implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Nome")
	private java.lang.String nome;
	@org.kie.api.definition.type.Label("Pontos")
	private java.lang.Integer pontos;
	@org.kie.api.definition.type.Label("Resultado")
	private java.lang.String resultado;

	public Pessoa() {
	}

	public java.lang.String getNome() {
		return this.nome;
	}

	public void setNome(java.lang.String nome) {
		this.nome = nome;
	}

	public java.lang.Integer getPontos() {
		return this.pontos;
	}

	public void setPontos(java.lang.Integer pontos) {
		this.pontos = pontos;
	}

	public java.lang.String getResultado() {
		return this.resultado;
	}

	public void setResultado(java.lang.String resultado) {
		this.resultado = resultado;
	}

	public Pessoa(java.lang.String nome, java.lang.Integer pontos,
			java.lang.String resultado) {
		this.nome = nome;
		this.pontos = pontos;
		this.resultado = resultado;
	}

}